verifyDepsBeforeRun: install

packages:
  - 'apps/**'
  - 'packages/**'
  - 'tools/**'
  - 'scripts'
  - '!apps/**/out'
  - '!apps/**/dist/**'

allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  less: true
  nx: true
  unrs-resolver: true

registries:
  https://npm.pkg.github.com:
    scopes: ['@thdk']
